### ISSUE TITLE
[Feat] Gateway 조사 및 공유

### ISSUE THREAD

**Issue by SongGwanSeok** [edu-pi/Backend-User-Server#8]
## 📝 Description
**무엇을?**
- Gateway 조사 및 공유

**왜?**
-Gateway를 이용한 로그인 구현

## ❗️Todo
- [ ] 
- [ ] 
- [ ]

## ETC
기타사항

**Comment by ujkkk** [comment]
# API GateWay
#게이트웨이
**Reverse Proxy**

1. 요청들을 라우팅한다.
2. 나가는 명단을 로깅할 수 있다
3. 인증 및 권한 부여

## Gateway 종류
1. Netflix zuul
2. Amazon API
3. Spring Cloud Gateway - 비동기가 적용된 게이트 웨이
![image 4](https://github.com/user-attachments/assets/9dd79908-3b68-4115-a4d8-c3172602da6e)

### Spring Cloud Gateway(SCG)
#게이트웨이/SCG
**Spring Reactive 환경에 구현된 API Gateway**
![](image%202.png)

## 3가지 옵션
📌 **Route** 응답을 보낼 목적지 uri와 필터 항목을 식별하기 위한 ID로 구성되어 있고 **라우팅 목적지**를 의미한다.
📌 **Predicate** 요청을 처리하기 전 **HTTP 요청이 정의된 조건에 부합하는지 검사**하며 Java 8의 Function Predicate 이다.
📌 **Filter** 게이트웨이에서 받은 **요청과 응답을 수정하는 역할**로 Spring Framework의 **WebFilter** 인스턴스이다.

```
# application.yml 예시

spring:
  cloud:
      gateway:
        default-filters:
          - name: GlobalFilter
            agrs:
            preLogger: true
            postLogger: true 
        routes:
          - id: product-service
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/product/**
            filters:             
              - name: UserFilter              
                args:                
                  baseMessage: productFilter                 
                  preLogger: true                
                  postLogger: true

```
구성이 디폴트로 적용되는 **GlobalFilter**와 각 서비스에 적용할 수 있는 내부 **ServiceFilter**로 구성

![](image%204.png)

### [ Spring Cloud Gateway 장점과 단점 ]
* 장점
  * 요청을 다른 서버로 라우팅시키는 부분을 간단한 yaml 파일로 완성할 수 있음
  * Non-Blocking 기술 기반이라 라우팅에 집중된(I/O 작업이 많은) 프로젝트에 최고의 성능을 보일 수 있음
  * 라우티 전/후에 손쉽게 부가 기능을 추가할 수 있음(GatewayFilter를 등록할 수 있고, 이미 많은 필터를 제공해주고 있음) ex) 헤더 추가 필터, RateLimit 필터 등

* 단점
  * 
  * 추가 기능의 구현을 WebFlux 기반(리액티브)으로 작성해야 하므로 어려울 수 있음
  * 라우팅 대상 서버가 많아진다면 관리가 어려울 수 있음

⠀출처: ~[https://mangkyu.tistory.com/230](https://mangkyu.tistory.com/230)~ [MangKyu's Diary:티스토리]


##### 모든 클라이언트는 각 서비스의 엔드포인트 대신 API Gateway로 요청을 전달하여 관리가 용이해 진다
### 엔드포인트 서버에서 공통으로 필요한인증/인가, 사용량 제어, 요청/응답 변조 등의 다양한 기능을 플러그인 형태로 제공

### API Gateway - 제공 API 유형
API Gateway에서 제공하는 API는 대표적으로 3종류가 있다.
* HTTP API : API 프록시 기능정도만 필요할 때 적합. 단순 / 저렴하고 빠르다.
* REST API : API 관리 기능, 요청/응답에 대한 제어가 필요할 경우 적합, 복잡 / 비싸고 느리다.
* WebSocket API : 웹소켓 용도. 실시간 애플리케이션에서 주로 사용한다.


### **HTTP API**
* HTTP를 통신 방식으로 사용하는 API를 HTTP API라고 한다.
* HTTP API는 Endpoint를 API gateway로 활용하여 HTTP 요청을 통해서 서버에 접근할 수 있도록 만들어준다.
* HTTP API는 데이터만 주고 받고 UI 화면이 필요하면 클라이언트가 별도로 처리한다. 대게 앱/웹/서버 to 서버에서 사용된다.
* 대부분의 Web API가 HTTP API로 이루어지고 있다.
![R1280x0](https://github.com/user-attachments/assets/7b87c57f-40dc-460e-a4b0-35d2cd9a6e92)
요청 하면 그냥 상품에 대한 데이터만 내려준다. 이렇게 데이터만 주고 받는 것을 HTTP API라고 한다.
![image 3](https://github.com/user-attachments/assets/629b41b0-f7db-41e8-8c42-ae0d4fb953f4)

**API Gateway 실전 사용 (HTTP API)**
출처: ~[https://inpa.tistory.com/entry/AWS-📚-API-Gateway-개념-기본-사용법-정리](https://inpa.tistory.com/entry/AWS-%F0%9F%93%9A-API-Gateway-%EA%B0%9C%EB%85%90-%EA%B8%B0%EB%B3%B8-%EC%82%AC%EC%9A%A9%EB%B2%95-%EC%A0%95%EB%A6%AC)~ [Inpa Dev 👨‍💻:티스토리]
- Amazon API 사용 방법 잘 나와 있음


## AWS API Gateway vs spring cloud Gateway
AWS API Gateway 장점
* Spring Cloud Gateway 인스턴스를 유지 관리, 구성, 모니터링 및 운영하는 데 드는 모든 운영 비용이 제거됩니다.
* 장애 조치 기능이 있어 가용성이 매우 높습니다.
* 속도 제한, API 키, 캐싱, 권한 부여, 카나리아 테스트, 프록싱, 통합 매핑, 환경과 같은 즉각적인 기능을 제공합니다.
* 매우 매우 저렴합니다(3.50 x MM 요청).

⠀Spring Cloud Function 장점
* 애플리케이션 코드 자체 내에서 API를 코드로 정의합니다.
* 예를 들어 Spring 내의 생태계 통합을 활용하여 개발자의 PC에서 로컬로 실행할 수 있습니다.

⠀API Gateway 사용의 단점:
* 새로운 API를 배포하는 것은 Spring Cloud Gateway를 사용하는 것보다 더 어렵습니다(각각의 새로운 리소스/메서드를 구성해야 함)
* 이제 비용은 요청 수에 따라 결정됩니다. 월 9억 건의 API가 있는 경우 비용이 많이 들 수 있습니다.
* 공급업체 잠금

⠀Spring Cloud Function을 사용하는 단점:
* 유지 보수의 운영 비용
* 단일 실패 지점


## **어떤 게이트웨이를 써야하나요?**
정답은 없다. 사용자가 상황에 맞게 각 기술 문서들을 보고 결정해야한다. 
1. KrakenD(크라켄)** 공식 문서가 상당히 정리가 잘되있다. 의존성이 없고 JSON 파일로 세팅이 끝난다. zero trust 정책 - 각 API마다 header 정보를 일일히 넣어줘야 한다. 플러그인 적용 가능 header에 크라켄이 추가되서 날아온다. 로그 기본 세팅이 너무 빈약하다. 
2. kong(콩) 많은 레퍼런스들이 있다. 리소스를 많이 잡아먹는다. ex) 1개만 띄워도 1GB를 잡아먹는다. RDB는 오직 PostgreSQL과 호환된다. 엄청나게 많은 플러그인이 지원된다.
3. Spring Cloud Gateway 자바를 썻다면 바로 채택했을 예정이지만 우리 팀 스택은 자바가 아니라 노드라 인프라 세팅에 어려움을 겪을거 같아 바로 탈락시켰다.
4. Tyk 공식 문서가 너무 조잡하다. 국내 사용풀이 너무 적어 관련 자료들을 얻기 쉽지 않다.
